/* Conteúdo editorial derivado exclusivamente dos PDFs anexados.
 * Cada questão mantém sua fonte para revisão humana e manutenção independente da interface.
 * Níveis: 1 reconhecimento, 2 aplicação, 3 diagnóstico e detalhes. */
window.FlowData = {
  categories: [
    {
      id: "arquivos",
      name: "Navegação e arquivos",
      number: "01",
      title: "Encontre seu caminho",
      description: "Organize a área de trabalho de um laboratório.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "texto",
      name: "Texto e redirecionamento",
      number: "02",
      title: "Conecte as saídas",
      description: "Transforme comandos isolados em uma rotina útil.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "permissoes",
      name: "Permissões e acesso",
      number: "03",
      title: "Proteja o laboratório",
      description: "Distribua acesso sem abrir mão do controle.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "usuarios",
      name: "Usuários e grupos",
      number: "04",
      title: "Prepare a equipe",
      description: "Cada pessoa com a identidade e o acesso adequados.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "processos",
      name: "Processos",
      number: "05",
      title: "Observe o sistema",
      description: "Descubra o que está em execução e controle as tarefas.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "redes",
      name: "Redes e diagnóstico",
      number: "06",
      title: "Reconecte os pontos",
      description: "Investigue interfaces, endereços e tráfego.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "ssh",
      name: "SSH e administração",
      number: "07",
      title: "Administre à distância",
      description: "Entre com segurança e acompanhe os serviços.",
      source: "SSH (3).pdf",
    },
    {
      id: "sistema",
      name: "Kernel e hardware",
      number: "08",
      title: "Olhe por dentro",
      description: "Observe os componentes que sustentam o sistema.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "distros",
      name: "Distribuições e pacotes",
      number: "09",
      title: "Escolha as ferramentas",
      description: "Reconheça famílias e seus gerenciadores de pacotes.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
  ],
  questions: [
    {
      id: "arquivos-1",
      category: "arquivos",
      level: 1,
      prompt: "Qual é a finalidade de pwd?",
      code: "pwd",
      answer: "Mostrar o caminho completo do diretório atual",
      options: [
        "Mostrar o caminho completo do diretório atual",
        "Listar detalhes e arquivos ocultos",
        "Subir um nível na árvore de diretórios",
        "Voltar ao diretório pessoal",
      ],
      explanation: "Mostra o diretório de trabalho atual.",
      source: "Jonathan Eleodoro - Exercícios.pdf",
    },
    {
      id: "arquivos-2",
      category: "arquivos",
      level: 1,
      prompt: "Qual é a finalidade de ls -la?",
      code: "ls -la",
      answer: "Listar detalhes e arquivos ocultos",
      options: [
        "Listar detalhes e arquivos ocultos",
        "Subir um nível na árvore de diretórios",
        "Voltar ao diretório pessoal",
        "Criar uma hierarquia de diretórios",
      ],
      explanation:
        "-l usa o formato longo; -a inclui entradas iniciadas com ponto.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-3",
      category: "arquivos",
      level: 1,
      prompt: "Qual é a finalidade de cd ..?",
      code: "cd ..",
      answer: "Subir um nível na árvore de diretórios",
      options: [
        "Subir um nível na árvore de diretórios",
        "Voltar ao diretório pessoal",
        "Criar uma hierarquia de diretórios",
        "Remover um diretório vazio",
      ],
      explanation: ".. representa o diretório pai.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-4",
      category: "arquivos",
      level: 1,
      prompt: "Qual é a finalidade de cd ~?",
      code: "cd ~",
      answer: "Voltar ao diretório pessoal",
      options: [
        "Voltar ao diretório pessoal",
        "Criar uma hierarquia de diretórios",
        "Remover um diretório vazio",
        "Criar um arquivo vazio inexistente",
      ],
      explanation: "O shell expande ~ para o diretório pessoal do usuário.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-5",
      category: "arquivos",
      level: 2,
      prompt: "Qual é a finalidade de mkdir -p?",
      code: "mkdir -p projeto/aulas",
      answer: "Criar uma hierarquia de diretórios",
      options: [
        "Criar uma hierarquia de diretórios",
        "Remover um diretório vazio",
        "Criar um arquivo vazio inexistente",
        "Copiar uma árvore de diretórios",
      ],
      explanation: "-p cria os diretórios pais necessários.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-6",
      category: "arquivos",
      level: 1,
      prompt: "Qual é a finalidade de rmdir?",
      code: "rmdir vazio",
      answer: "Remover um diretório vazio",
      options: [
        "Remover um diretório vazio",
        "Criar um arquivo vazio inexistente",
        "Copiar uma árvore de diretórios",
        "Mover ou renomear um arquivo",
      ],
      explanation: "Falha se o diretório tiver conteúdo.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-7",
      category: "arquivos",
      level: 1,
      prompt: "Qual é a finalidade de touch?",
      code: "touch aula.txt",
      answer: "Criar um arquivo vazio inexistente",
      options: [
        "Criar um arquivo vazio inexistente",
        "Copiar uma árvore de diretórios",
        "Mover ou renomear um arquivo",
        "Remover um diretório e seu conteúdo",
      ],
      explanation:
        "Se o arquivo existe, touch atualiza seus timestamps; não apaga seu conteúdo.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-8",
      category: "arquivos",
      level: 2,
      prompt: "Qual é a finalidade de cp -r?",
      code: "cp -r projeto copia",
      answer: "Copiar uma árvore de diretórios",
      options: [
        "Copiar uma árvore de diretórios",
        "Mover ou renomear um arquivo",
        "Remover um diretório e seu conteúdo",
        "Localizar arquivos pelo nome",
      ],
      explanation: "-r percorre os subdiretórios recursivamente.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-9",
      category: "arquivos",
      level: 1,
      prompt: "Qual é a finalidade de mv?",
      code: "mv aula.txt revisao.txt",
      answer: "Mover ou renomear um arquivo",
      options: [
        "Mover ou renomear um arquivo",
        "Remover um diretório e seu conteúdo",
        "Localizar arquivos pelo nome",
        "Voltar ao diretório anterior",
      ],
      explanation: "O destino determina se haverá mudança de local ou de nome.",
      source: "Jonathan Eleodoro - Exercícios.pdf",
    },
    {
      id: "arquivos-10",
      category: "arquivos",
      level: 2,
      prompt: "Qual é a finalidade de rm -r?",
      code: "rm -r teste",
      answer: "Remover um diretório e seu conteúdo",
      options: [
        "Remover um diretório e seu conteúdo",
        "Localizar arquivos pelo nome",
        "Voltar ao diretório anterior",
        "Mostrar o caminho completo do diretório atual",
      ],
      explanation:
        "A remoção é recursiva. Confira o caminho antes de executar em um sistema real.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-11",
      category: "arquivos",
      level: 2,
      prompt: "Qual é a finalidade de find?",
      code: 'find /etc -name "*.conf"',
      answer: "Localizar arquivos pelo nome",
      options: [
        "Localizar arquivos pelo nome",
        "Voltar ao diretório anterior",
        "Mostrar o caminho completo do diretório atual",
        "Listar detalhes e arquivos ocultos",
      ],
      explanation: "A busca percorre a árvore a partir do caminho indicado.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "arquivos-12",
      category: "arquivos",
      level: 2,
      prompt: "Qual é a finalidade de cd -?",
      code: "cd -",
      answer: "Voltar ao diretório anterior",
      options: [
        "Voltar ao diretório anterior",
        "Mostrar o caminho completo do diretório atual",
        "Listar detalhes e arquivos ocultos",
        "Subir um nível na árvore de diretórios",
      ],
      explanation:
        "Usa o diretório de trabalho anterior armazenado pelo shell.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "texto-1",
      category: "texto",
      level: 1,
      prompt: "Qual é a finalidade de cat?",
      code: "cat aula.txt",
      answer: "Exibir ou concatenar conteúdo de arquivos",
      options: [
        "Exibir ou concatenar conteúdo de arquivos",
        "Mostrar as três primeiras linhas",
        "Mostrar as dez últimas linhas",
        "Selecionar linhas que correspondem a um padrão",
      ],
      explanation: "Lê os arquivos e escreve seu conteúdo na saída padrão.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-2",
      category: "texto",
      level: 1,
      prompt: "Qual é a finalidade de head -n 3?",
      code: "head -n 3 /etc/passwd",
      answer: "Mostrar as três primeiras linhas",
      options: [
        "Mostrar as três primeiras linhas",
        "Mostrar as dez últimas linhas",
        "Selecionar linhas que correspondem a um padrão",
        "Ordenar linhas de texto",
      ],
      explanation: "-n define a quantidade de linhas iniciais.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "texto-3",
      category: "texto",
      level: 1,
      prompt: "Qual é a finalidade de tail -n 10?",
      code: "tail -n 10 /var/log/syslog",
      answer: "Mostrar as dez últimas linhas",
      options: [
        "Mostrar as dez últimas linhas",
        "Selecionar linhas que correspondem a um padrão",
        "Ordenar linhas de texto",
        "Contar linhas delimitadas por nova linha",
      ],
      explanation: "Útil para consultar o final de um arquivo de log.",
      source: "Jonathan Eleodoro - Exercícios.pdf",
    },
    {
      id: "texto-4",
      category: "texto",
      level: 1,
      prompt: "Qual é a finalidade de grep?",
      code: "grep error sistema.log",
      answer: "Selecionar linhas que correspondem a um padrão",
      options: [
        "Selecionar linhas que correspondem a um padrão",
        "Ordenar linhas de texto",
        "Contar linhas delimitadas por nova linha",
        "Redirecionar a saída padrão sobrescrevendo o destino",
      ],
      explanation: "Filtra linhas; não altera o arquivo de entrada.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-5",
      category: "texto",
      level: 1,
      prompt: "Qual é a finalidade de sort?",
      code: "sort nomes.txt",
      answer: "Ordenar linhas de texto",
      options: [
        "Ordenar linhas de texto",
        "Contar linhas delimitadas por nova linha",
        "Redirecionar a saída padrão sobrescrevendo o destino",
        "Acrescentar a saída padrão ao final do destino",
      ],
      explanation: "A ordem depende da localidade; números podem exigir -n.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-6",
      category: "texto",
      level: 1,
      prompt: "Qual é a finalidade de wc -l?",
      code: "wc -l nomes.txt",
      answer: "Contar linhas delimitadas por nova linha",
      options: [
        "Contar linhas delimitadas por nova linha",
        "Redirecionar a saída padrão sobrescrevendo o destino",
        "Acrescentar a saída padrão ao final do destino",
        "Ler a entrada padrão a partir de um arquivo",
      ],
      explanation: "Conta os caracteres de nova linha da entrada.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-7",
      category: "texto",
      level: 2,
      prompt: "Qual é a finalidade de >?",
      code: "ls -la > lista.txt",
      answer: "Redirecionar a saída padrão sobrescrevendo o destino",
      options: [
        "Redirecionar a saída padrão sobrescrevendo o destino",
        "Acrescentar a saída padrão ao final do destino",
        "Ler a entrada padrão a partir de um arquivo",
        "Conectar a saída padrão à entrada do próximo comando",
      ],
      explanation: "Cria o arquivo ou trunca o existente antes da execução.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-8",
      category: "texto",
      level: 2,
      prompt: "Qual é a finalidade de >>?",
      code: "date >> registro.txt",
      answer: "Acrescentar a saída padrão ao final do destino",
      options: [
        "Acrescentar a saída padrão ao final do destino",
        "Ler a entrada padrão a partir de um arquivo",
        "Conectar a saída padrão à entrada do próximo comando",
        "Redirecionar apenas a saída de erro sobrescrevendo o destino",
      ],
      explanation: "Preserva o conteúdo anterior e acrescenta a nova saída.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-9",
      category: "texto",
      level: 2,
      prompt: "Qual é a finalidade de <?",
      code: "sort < nomes.txt",
      answer: "Ler a entrada padrão a partir de um arquivo",
      options: [
        "Ler a entrada padrão a partir de um arquivo",
        "Conectar a saída padrão à entrada do próximo comando",
        "Redirecionar apenas a saída de erro sobrescrevendo o destino",
        "Acrescentar apenas a saída de erro ao destino",
      ],
      explanation:
        "O programa recebe o conteúdo do arquivo pela entrada padrão.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-10",
      category: "texto",
      level: 2,
      prompt: "Qual é a finalidade de |?",
      code: "cat nomes.txt | sort",
      answer: "Conectar a saída padrão à entrada do próximo comando",
      options: [
        "Conectar a saída padrão à entrada do próximo comando",
        "Redirecionar apenas a saída de erro sobrescrevendo o destino",
        "Acrescentar apenas a saída de erro ao destino",
        "Redirecionar saída padrão e erros no Bash",
      ],
      explanation: "O pipe transporta dados; erros não entram nele por padrão.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-11",
      category: "texto",
      level: 2,
      prompt: "Qual é a finalidade de 2>?",
      code: "cat ausente.txt 2> erros.log",
      answer: "Redirecionar apenas a saída de erro sobrescrevendo o destino",
      options: [
        "Redirecionar apenas a saída de erro sobrescrevendo o destino",
        "Acrescentar apenas a saída de erro ao destino",
        "Redirecionar saída padrão e erros no Bash",
        "Exibir a saída e gravá-la em arquivo",
      ],
      explanation: "O descritor 2 corresponde à saída de erro.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-12",
      category: "texto",
      level: 3,
      prompt: "Qual é a finalidade de 2>>?",
      code: "cat ausente.txt 2>> erros.log",
      answer: "Acrescentar apenas a saída de erro ao destino",
      options: [
        "Acrescentar apenas a saída de erro ao destino",
        "Redirecionar saída padrão e erros no Bash",
        "Exibir a saída e gravá-la em arquivo",
        "Executar o próximo comando apenas se o anterior tiver sucesso",
      ],
      explanation: "Combina o descritor 2 com o operador de acréscimo.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-13",
      category: "texto",
      level: 3,
      prompt: "Qual é a finalidade de &>?",
      code: "ls /ausente &> tudo.log",
      answer: "Redirecionar saída padrão e erros no Bash",
      options: [
        "Redirecionar saída padrão e erros no Bash",
        "Exibir a saída e gravá-la em arquivo",
        "Executar o próximo comando apenas se o anterior tiver sucesso",
        "Exibir ou concatenar conteúdo de arquivos",
      ],
      explanation: "É sintaxe do Bash; não deve ser presumida para todo shell.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-14",
      category: "texto",
      level: 2,
      prompt: "Qual é a finalidade de tee?",
      code: "ls | tee lista.txt",
      answer: "Exibir a saída e gravá-la em arquivo",
      options: [
        "Exibir a saída e gravá-la em arquivo",
        "Executar o próximo comando apenas se o anterior tiver sucesso",
        "Exibir ou concatenar conteúdo de arquivos",
        "Mostrar as três primeiras linhas",
      ],
      explanation: "Recebe entrada padrão e a copia para a tela e o arquivo.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "texto-15",
      category: "texto",
      level: 3,
      prompt: "Qual é a finalidade de &&?",
      code: "mkdir projeto && cd projeto",
      answer: "Executar o próximo comando apenas se o anterior tiver sucesso",
      options: [
        "Executar o próximo comando apenas se o anterior tiver sucesso",
        "Exibir ou concatenar conteúdo de arquivos",
        "Mostrar as três primeiras linhas",
        "Mostrar as dez últimas linhas",
      ],
      explanation: "O shell verifica o status de saída zero.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "permissoes-1",
      category: "permissoes",
      level: 1,
      prompt: "Qual é a finalidade de chmod?",
      code: "chmod 640 documento.txt",
      answer: "Alterar permissões de acesso",
      options: [
        "Alterar permissões de acesso",
        "Alterar o proprietário de um arquivo",
        "Alterar somente o grupo proprietário",
        "Conceder rwx ao dono, r-x ao grupo e nada aos outros",
      ],
      explanation: "Aceita modos simbólicos e octais.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-2",
      category: "permissoes",
      level: 1,
      prompt: "Qual é a finalidade de chown?",
      code: "chown aluno:turma documento.txt",
      answer: "Alterar o proprietário de um arquivo",
      options: [
        "Alterar o proprietário de um arquivo",
        "Alterar somente o grupo proprietário",
        "Conceder rwx ao dono, r-x ao grupo e nada aos outros",
        "Adicionar execução ao grupo sem alterar os demais bits",
      ],
      explanation: "Pode também alterar o grupo usando dono:grupo.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-3",
      category: "permissoes",
      level: 1,
      prompt: "Qual é a finalidade de chgrp?",
      code: "chgrp turma documento.txt",
      answer: "Alterar somente o grupo proprietário",
      options: [
        "Alterar somente o grupo proprietário",
        "Conceder rwx ao dono, r-x ao grupo e nada aos outros",
        "Adicionar execução ao grupo sem alterar os demais bits",
        "Retirar escrita dos outros usuários",
      ],
      explanation: "Mantém o usuário proprietário.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-4",
      category: "permissoes",
      level: 2,
      prompt: "Qual é a finalidade de chmod 750?",
      code: "chmod 750 projeto",
      answer: "Conceder rwx ao dono, r-x ao grupo e nada aos outros",
      options: [
        "Conceder rwx ao dono, r-x ao grupo e nada aos outros",
        "Adicionar execução ao grupo sem alterar os demais bits",
        "Retirar escrita dos outros usuários",
        "Ativar o sticky bit em um diretório",
      ],
      explanation: "Os valores r=4, w=2 e x=1 são somados em cada classe.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-5",
      category: "permissoes",
      level: 2,
      prompt: "Qual é a finalidade de chmod g+x?",
      code: "chmod g+x programa",
      answer: "Adicionar execução ao grupo sem alterar os demais bits",
      options: [
        "Adicionar execução ao grupo sem alterar os demais bits",
        "Retirar escrita dos outros usuários",
        "Ativar o sticky bit em um diretório",
        "Ativar SGID em um diretório compartilhado",
      ],
      explanation:
        "A operação simbólica + preserva as permissões não mencionadas.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-6",
      category: "permissoes",
      level: 2,
      prompt: "Qual é a finalidade de chmod o-w?",
      code: "chmod o-w documento.txt",
      answer: "Retirar escrita dos outros usuários",
      options: [
        "Retirar escrita dos outros usuários",
        "Ativar o sticky bit em um diretório",
        "Ativar SGID em um diretório compartilhado",
        "Ativar SUID em um executável",
      ],
      explanation: "o indica outros; -w remove somente escrita.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-7",
      category: "permissoes",
      level: 3,
      prompt: "Qual é a finalidade de chmod +t?",
      code: "chmod +t compartilhado",
      answer: "Ativar o sticky bit em um diretório",
      options: [
        "Ativar o sticky bit em um diretório",
        "Ativar SGID em um diretório compartilhado",
        "Ativar SUID em um executável",
        "Restringir permissões iniciais de novos arquivos ao dono",
      ],
      explanation:
        "Restringe exclusão e renomeação ao dono do arquivo, dono do diretório ou usuário privilegiado. As permissões normais continuam valendo.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-8",
      category: "permissoes",
      level: 3,
      prompt: "Qual é a finalidade de chmod g+s?",
      code: "chmod g+s projeto",
      answer: "Ativar SGID em um diretório compartilhado",
      options: [
        "Ativar SGID em um diretório compartilhado",
        "Ativar SUID em um executável",
        "Restringir permissões iniciais de novos arquivos ao dono",
        "Alterar permissões de acesso",
      ],
      explanation:
        "Novos arquivos herdam o grupo do diretório; isso não concede escrita automaticamente.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-9",
      category: "permissoes",
      level: 3,
      prompt: "Qual é a finalidade de chmod u+s?",
      code: "chmod u+s programa",
      answer: "Ativar SUID em um executável",
      options: [
        "Ativar SUID em um executável",
        "Restringir permissões iniciais de novos arquivos ao dono",
        "Alterar permissões de acesso",
        "Alterar o proprietário de um arquivo",
      ],
      explanation:
        "Em executáveis compatíveis, pode mudar o UID efetivo para o dono. Não use como solução geral de acesso.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "permissoes-10",
      category: "permissoes",
      level: 3,
      prompt: "Qual é a finalidade de umask 077?",
      code: "umask 077",
      answer: "Restringir permissões iniciais de novos arquivos ao dono",
      options: [
        "Restringir permissões iniciais de novos arquivos ao dono",
        "Alterar permissões de acesso",
        "Alterar o proprietário de um arquivo",
        "Alterar somente o grupo proprietário",
      ],
      explanation:
        "Com bases usuais 666 e 777, resulta em arquivos 600 e diretórios 700. A máscara remove bits.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "usuarios-1",
      category: "usuarios",
      level: 1,
      prompt: "Qual é a finalidade de whoami?",
      code: "whoami",
      answer: "Exibir o nome do usuário efetivo",
      options: [
        "Exibir o nome do usuário efetivo",
        "Consultar UID, GID e grupos de um usuário",
        "Listar sessões de usuários conectados",
        "Criar uma conta de usuário",
      ],
      explanation:
        "Identifica o usuário associado à identidade efetiva do processo.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-2",
      category: "usuarios",
      level: 1,
      prompt: "Qual é a finalidade de id?",
      code: "id aluno",
      answer: "Consultar UID, GID e grupos de um usuário",
      options: [
        "Consultar UID, GID e grupos de um usuário",
        "Listar sessões de usuários conectados",
        "Criar uma conta de usuário",
        "Definir ou alterar a senha de uma conta",
      ],
      explanation: "Sem argumento consulta o usuário atual.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-3",
      category: "usuarios",
      level: 1,
      prompt: "Qual é a finalidade de who?",
      code: "who",
      answer: "Listar sessões de usuários conectados",
      options: [
        "Listar sessões de usuários conectados",
        "Criar uma conta de usuário",
        "Definir ou alterar a senha de uma conta",
        "Criar um grupo",
      ],
      explanation: "Não é uma lista de todas as contas cadastradas.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-4",
      category: "usuarios",
      level: 1,
      prompt: "Qual é a finalidade de useradd?",
      code: "useradd -m aluno",
      answer: "Criar uma conta de usuário",
      options: [
        "Criar uma conta de usuário",
        "Definir ou alterar a senha de uma conta",
        "Criar um grupo",
        "Acrescentar um grupo suplementar preservando os demais",
      ],
      explanation: "Opções como -m e -s controlam diretório pessoal e shell.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-5",
      category: "usuarios",
      level: 1,
      prompt: "Qual é a finalidade de passwd?",
      code: "passwd aluno",
      answer: "Definir ou alterar a senha de uma conta",
      options: [
        "Definir ou alterar a senha de uma conta",
        "Criar um grupo",
        "Acrescentar um grupo suplementar preservando os demais",
        "Excluir conta e remover seu diretório pessoal",
      ],
      explanation:
        "Alterar senha de outro usuário exige privilégios adequados.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-6",
      category: "usuarios",
      level: 1,
      prompt: "Qual é a finalidade de groupadd?",
      code: "groupadd laboratorio",
      answer: "Criar um grupo",
      options: [
        "Criar um grupo",
        "Acrescentar um grupo suplementar preservando os demais",
        "Excluir conta e remover seu diretório pessoal",
        "Exigir alteração da senha no próximo login",
      ],
      explanation: "Depois da criação, o grupo pode receber membros.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-7",
      category: "usuarios",
      level: 2,
      prompt: "Qual é a finalidade de usermod -aG?",
      code: "usermod -aG laboratorio aluno",
      answer: "Acrescentar um grupo suplementar preservando os demais",
      options: [
        "Acrescentar um grupo suplementar preservando os demais",
        "Excluir conta e remover seu diretório pessoal",
        "Exigir alteração da senha no próximo login",
        "Renomear um grupo existente",
      ],
      explanation:
        "-a acrescenta; -G informa os grupos suplementares. Sem -a, a lista pode ser substituída.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-8",
      category: "usuarios",
      level: 3,
      prompt: "Qual é a finalidade de userdel -r?",
      code: "userdel -r aluno",
      answer: "Excluir conta e remover seu diretório pessoal",
      options: [
        "Excluir conta e remover seu diretório pessoal",
        "Exigir alteração da senha no próximo login",
        "Renomear um grupo existente",
        "Exibir o nome do usuário efetivo",
      ],
      explanation:
        "Revise dados e faça backup antes de excluir. Não procura todo arquivo do usuário no sistema.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-9",
      category: "usuarios",
      level: 3,
      prompt: "Qual é a finalidade de chage -d 0?",
      code: "chage -d 0 aluno",
      answer: "Exigir alteração da senha no próximo login",
      options: [
        "Exigir alteração da senha no próximo login",
        "Renomear um grupo existente",
        "Exibir o nome do usuário efetivo",
        "Consultar UID, GID e grupos de um usuário",
      ],
      explanation: "Define a última troca de senha para o início da contagem.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "usuarios-10",
      category: "usuarios",
      level: 2,
      prompt: "Qual é a finalidade de groupmod -n?",
      code: "groupmod -n infra suporte",
      answer: "Renomear um grupo existente",
      options: [
        "Renomear um grupo existente",
        "Exibir o nome do usuário efetivo",
        "Consultar UID, GID e grupos de um usuário",
        "Listar sessões de usuários conectados",
      ],
      explanation: "O novo nome vem antes do nome atual.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "processos-1",
      category: "processos",
      level: 1,
      prompt: "Qual é a finalidade de ps aux?",
      code: "ps aux",
      answer: "Obter uma fotografia dos processos",
      options: [
        "Obter uma fotografia dos processos",
        "Acompanhar processos em uma tela atualizada",
        "Explorar processos em uma interface interativa",
        "Listar os jobs do shell atual",
      ],
      explanation:
        "É uma consulta pontual, não uma tela atualizada continuamente.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "processos-2",
      category: "processos",
      level: 1,
      prompt: "Qual é a finalidade de top?",
      code: "top",
      answer: "Acompanhar processos em uma tela atualizada",
      options: [
        "Acompanhar processos em uma tela atualizada",
        "Explorar processos em uma interface interativa",
        "Listar os jobs do shell atual",
        "Trazer um job ao primeiro plano",
      ],
      explanation: "Mostra atividade e consumo de recursos.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "processos-3",
      category: "processos",
      level: 1,
      prompt: "Qual é a finalidade de htop?",
      code: "htop",
      answer: "Explorar processos em uma interface interativa",
      options: [
        "Explorar processos em uma interface interativa",
        "Listar os jobs do shell atual",
        "Trazer um job ao primeiro plano",
        "Retomar um job suspenso em segundo plano",
      ],
      explanation: "Pode precisar de instalação; a disponibilidade varia.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "processos-4",
      category: "processos",
      level: 2,
      prompt: "Qual é a finalidade de jobs?",
      code: "jobs",
      answer: "Listar os jobs do shell atual",
      options: [
        "Listar os jobs do shell atual",
        "Trazer um job ao primeiro plano",
        "Retomar um job suspenso em segundo plano",
        "Solicitar encerramento de um processo por sinal",
      ],
      explanation: "Não lista todos os processos de todos os usuários.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "processos-5",
      category: "processos",
      level: 2,
      prompt: "Qual é a finalidade de fg?",
      code: "fg %1",
      answer: "Trazer um job ao primeiro plano",
      options: [
        "Trazer um job ao primeiro plano",
        "Retomar um job suspenso em segundo plano",
        "Solicitar encerramento de um processo por sinal",
        "Forçar o término de um processo sem tratamento do sinal",
      ],
      explanation: "O shell passa a aguardar o job selecionado.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "processos-6",
      category: "processos",
      level: 2,
      prompt: "Qual é a finalidade de bg?",
      code: "bg %1",
      answer: "Retomar um job suspenso em segundo plano",
      options: [
        "Retomar um job suspenso em segundo plano",
        "Solicitar encerramento de um processo por sinal",
        "Forçar o término de um processo sem tratamento do sinal",
        "Obter uma fotografia dos processos",
      ],
      explanation: "Trabalha com os jobs controlados pelo shell atual.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "processos-7",
      category: "processos",
      level: 2,
      prompt: "Qual é a finalidade de kill -TERM?",
      code: "kill -TERM 1234",
      answer: "Solicitar encerramento de um processo por sinal",
      options: [
        "Solicitar encerramento de um processo por sinal",
        "Forçar o término de um processo sem tratamento do sinal",
        "Obter uma fotografia dos processos",
        "Acompanhar processos em uma tela atualizada",
      ],
      explanation:
        "SIGTERM pode ser tratado pelo processo para encerrar de forma organizada.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "processos-8",
      category: "processos",
      level: 3,
      prompt: "Qual é a finalidade de kill -KILL?",
      code: "kill -KILL 1234",
      answer: "Forçar o término de um processo sem tratamento do sinal",
      options: [
        "Forçar o término de um processo sem tratamento do sinal",
        "Obter uma fotografia dos processos",
        "Acompanhar processos em uma tela atualizada",
        "Explorar processos em uma interface interativa",
      ],
      explanation:
        "SIGKILL não pode ser capturado pelo processo. Evite como primeira tentativa.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "redes-1",
      category: "redes",
      level: 1,
      prompt: "Qual é a finalidade de ip addr?",
      code: "ip addr",
      answer: "Consultar endereços das interfaces",
      options: [
        "Consultar endereços das interfaces",
        "Consultar a tabela de rotas",
        "Testar resposta a mensagens ICMP de eco",
        "Consultar sockets de rede",
      ],
      explanation: "Exibe endereços e informações associadas às interfaces.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-2",
      category: "redes",
      level: 1,
      prompt: "Qual é a finalidade de ip route?",
      code: "ip route",
      answer: "Consultar a tabela de rotas",
      options: [
        "Consultar a tabela de rotas",
        "Testar resposta a mensagens ICMP de eco",
        "Consultar sockets de rede",
        "Exibir interfaces e atributos de enlace",
      ],
      explanation: "Mostra caminhos e o gateway padrão quando configurado.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "redes-3",
      category: "redes",
      level: 1,
      prompt: "Qual é a finalidade de ping?",
      code: "ping -c 4 192.168.1.10",
      answer: "Testar resposta a mensagens ICMP de eco",
      options: [
        "Testar resposta a mensagens ICMP de eco",
        "Consultar sockets de rede",
        "Exibir interfaces e atributos de enlace",
        "Ativar administrativamente uma interface",
      ],
      explanation:
        "Ausência de resposta não prova indisponibilidade: ICMP pode estar filtrado.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-4",
      category: "redes",
      level: 2,
      prompt: "Qual é a finalidade de ss?",
      code: "ss -lnt",
      answer: "Consultar sockets de rede",
      options: [
        "Consultar sockets de rede",
        "Exibir interfaces e atributos de enlace",
        "Ativar administrativamente uma interface",
        "Capturar tráfego ICMP em uma interface",
      ],
      explanation:
        "Pode mostrar conexões e portas em escuta conforme as opções.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-5",
      category: "redes",
      level: 1,
      prompt: "Qual é a finalidade de ip link show?",
      code: "ip link show",
      answer: "Exibir interfaces e atributos de enlace",
      options: [
        "Exibir interfaces e atributos de enlace",
        "Ativar administrativamente uma interface",
        "Capturar tráfego ICMP em uma interface",
        "Limitar uma captura a cinquenta pacotes",
      ],
      explanation: "Ajuda a observar estado e endereços MAC.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-6",
      category: "redes",
      level: 2,
      prompt: "Qual é a finalidade de ip link set dev enp0s3 up?",
      code: "ip link set dev enp0s3 up",
      answer: "Ativar administrativamente uma interface",
      options: [
        "Ativar administrativamente uma interface",
        "Capturar tráfego ICMP em uma interface",
        "Limitar uma captura a cinquenta pacotes",
        "Capturar sem resolver endereços para nomes",
      ],
      explanation: "A ativação não configura, por si só, endereço IP ou rota.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-7",
      category: "redes",
      level: 2,
      prompt: "Qual é a finalidade de tcpdump -i eth0 icmp?",
      code: "tcpdump -i eth0 icmp",
      answer: "Capturar tráfego ICMP em uma interface",
      options: [
        "Capturar tráfego ICMP em uma interface",
        "Limitar uma captura a cinquenta pacotes",
        "Capturar sem resolver endereços para nomes",
        "Filtrar tráfego associado à porta 53",
      ],
      explanation:
        "O filtro icmp seleciona esse protocolo. Capturas reais exigem autorização e privilégios apropriados.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-8",
      category: "redes",
      level: 2,
      prompt: "Qual é a finalidade de tcpdump -c 50 -i eth0?",
      code: "tcpdump -c 50 -i eth0",
      answer: "Limitar uma captura a cinquenta pacotes",
      options: [
        "Limitar uma captura a cinquenta pacotes",
        "Capturar sem resolver endereços para nomes",
        "Filtrar tráfego associado à porta 53",
        "Consultar informações DNS",
      ],
      explanation: "-c define a quantidade antes do encerramento.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-9",
      category: "redes",
      level: 3,
      prompt: "Qual é a finalidade de tcpdump -n -i eth0?",
      code: "tcpdump -n -i eth0",
      answer: "Capturar sem resolver endereços para nomes",
      options: [
        "Capturar sem resolver endereços para nomes",
        "Filtrar tráfego associado à porta 53",
        "Consultar informações DNS",
        "Inspecionar respostas DNS detalhadas",
      ],
      explanation: "-n evita a conversão de endereços em nomes.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-10",
      category: "redes",
      level: 3,
      prompt: "Qual é a finalidade de tcpdump -i eth0 port 53?",
      code: "tcpdump -i eth0 port 53",
      answer: "Filtrar tráfego associado à porta 53",
      options: [
        "Filtrar tráfego associado à porta 53",
        "Consultar informações DNS",
        "Inspecionar respostas DNS detalhadas",
        "Criar um namespace de rede",
      ],
      explanation:
        "O filtro usa a porta; não garante que todo pacote seja uma consulta DNS legítima.",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      id: "redes-11",
      category: "redes",
      level: 2,
      prompt: "Qual é a finalidade de nslookup?",
      code: "nslookup servidor.exemplo",
      answer: "Consultar informações DNS",
      options: [
        "Consultar informações DNS",
        "Inspecionar respostas DNS detalhadas",
        "Criar um namespace de rede",
        "Consultar endereços das interfaces",
      ],
      explanation: "Permite consultar nomes junto a um servidor DNS.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "redes-12",
      category: "redes",
      level: 3,
      prompt: "Qual é a finalidade de dig?",
      code: "dig servidor.exemplo",
      answer: "Inspecionar respostas DNS detalhadas",
      options: [
        "Inspecionar respostas DNS detalhadas",
        "Criar um namespace de rede",
        "Consultar endereços das interfaces",
        "Consultar a tabela de rotas",
      ],
      explanation: "Mostra informações da consulta e registros retornados.",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      id: "redes-13",
      category: "redes",
      level: 3,
      prompt: "Qual é a finalidade de ip netns add?",
      code: "ip netns add pc1",
      answer: "Criar um namespace de rede",
      options: [
        "Criar um namespace de rede",
        "Consultar endereços das interfaces",
        "Consultar a tabela de rotas",
        "Testar resposta a mensagens ICMP de eco",
      ],
      explanation:
        "Permite isolar interfaces, rotas e outros recursos de rede.",
      source: "Jonathan Eleodoro - Projeto.pdf",
    },
    {
      id: "ssh-1",
      category: "ssh",
      level: 1,
      prompt: "Qual é a finalidade de ssh aluno@192.168.1.10?",
      code: "ssh aluno@192.168.1.10",
      answer: "Iniciar uma sessão SSH como aluno",
      options: [
        "Iniciar uma sessão SSH como aluno",
        "Consultar o estado do serviço SSH no cenário Debian",
        "Iniciar o serviço SSH no cenário Debian",
        "Abrir uma sessão de login do usuário root",
      ],
      explanation: "O cliente conecta ao servidor usando o usuário indicado.",
      source: "SSH (3).pdf",
    },
    {
      id: "ssh-2",
      category: "ssh",
      level: 1,
      prompt: "Qual é a finalidade de systemctl status ssh?",
      code: "systemctl status ssh",
      answer: "Consultar o estado do serviço SSH no cenário Debian",
      options: [
        "Consultar o estado do serviço SSH no cenário Debian",
        "Iniciar o serviço SSH no cenário Debian",
        "Abrir uma sessão de login do usuário root",
        "Executar um comando com a identidade autorizada pela política",
      ],
      explanation: "O nome da unidade pode variar entre distribuições.",
      source: "SSH (3).pdf",
    },
    {
      id: "ssh-3",
      category: "ssh",
      level: 2,
      prompt: "Qual é a finalidade de systemctl start ssh?",
      code: "systemctl start ssh",
      answer: "Iniciar o serviço SSH no cenário Debian",
      options: [
        "Iniciar o serviço SSH no cenário Debian",
        "Abrir uma sessão de login do usuário root",
        "Executar um comando com a identidade autorizada pela política",
        "Editar a política sudoers com verificação de sintaxe",
      ],
      explanation: "Iniciar agora não é o mesmo que habilitar no boot.",
      source: "SSH (3).pdf",
    },
    {
      id: "ssh-4",
      category: "ssh",
      level: 2,
      prompt: "Qual é a finalidade de su -?",
      code: "su -",
      answer: "Abrir uma sessão de login do usuário root",
      options: [
        "Abrir uma sessão de login do usuário root",
        "Executar um comando com a identidade autorizada pela política",
        "Editar a política sudoers com verificação de sintaxe",
        "Testar a configuração do Nginx antes de reiniciar",
      ],
      explanation:
        "O hífen solicita ambiente de login; não é equivalente a preservar o ambiente da sessão atual.",
      source: "Su -   e Visudo.pdf",
    },
    {
      id: "ssh-5",
      category: "ssh",
      level: 1,
      prompt: "Qual é a finalidade de sudo?",
      code: "sudo whoami",
      answer: "Executar um comando com a identidade autorizada pela política",
      options: [
        "Executar um comando com a identidade autorizada pela política",
        "Editar a política sudoers com verificação de sintaxe",
        "Testar a configuração do Nginx antes de reiniciar",
        "Consultar uma URL a partir do terminal",
      ],
      explanation:
        "O acesso depende da configuração; não é uma permissão ilimitada para qualquer usuário.",
      source: "Su -   e Visudo.pdf",
    },
    {
      id: "ssh-6",
      category: "ssh",
      level: 3,
      prompt: "Qual é a finalidade de visudo?",
      code: "visudo",
      answer: "Editar a política sudoers com verificação de sintaxe",
      options: [
        "Editar a política sudoers com verificação de sintaxe",
        "Testar a configuração do Nginx antes de reiniciar",
        "Consultar uma URL a partir do terminal",
        "Iniciar uma sessão SSH como aluno",
      ],
      explanation:
        "Ajuda a evitar erros de sintaxe na política administrativa.",
      source: "Su -   e Visudo.pdf",
    },
    {
      id: "ssh-7",
      category: "ssh",
      level: 3,
      prompt: "Qual é a finalidade de nginx -t?",
      code: "nginx -t",
      answer: "Testar a configuração do Nginx antes de reiniciar",
      options: [
        "Testar a configuração do Nginx antes de reiniciar",
        "Consultar uma URL a partir do terminal",
        "Iniciar uma sessão SSH como aluno",
        "Consultar o estado do serviço SSH no cenário Debian",
      ],
      explanation:
        "Verifique a validação antes de aplicar uma mudança no serviço.",
      source:
        "Jonathan Eleodoro - Atividade - Aula 3 Dois Servidores Virtuais.pdf",
    },
    {
      id: "ssh-8",
      category: "ssh",
      level: 2,
      prompt: "Qual é a finalidade de curl?",
      code: "curl http://10.0.0.100",
      answer: "Consultar uma URL a partir do terminal",
      options: [
        "Consultar uma URL a partir do terminal",
        "Iniciar uma sessão SSH como aluno",
        "Consultar o estado do serviço SSH no cenário Debian",
        "Iniciar o serviço SSH no cenário Debian",
      ],
      explanation:
        "No laboratório, permite testar a resposta do servidor HTTP.",
      source:
        "Jonathan Eleodoro - Atividade - Aula 3 Dois Servidores Virtuais.pdf",
    },
    {
      id: "sistema-1",
      category: "sistema",
      level: 1,
      prompt: "Qual é a finalidade de uname -a?",
      code: "uname -a",
      answer: "Consultar informações do kernel e da arquitetura",
      options: [
        "Consultar informações do kernel e da arquitetura",
        "Consultar detalhes da CPU",
        "Listar dispositivos conectados ao barramento PCI",
        "Listar módulos carregados no kernel",
      ],
      explanation:
        "Mostra diversos dados do sistema; não substitui uma identificação completa da distribuição.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "sistema-2",
      category: "sistema",
      level: 1,
      prompt: "Qual é a finalidade de lscpu?",
      code: "lscpu",
      answer: "Consultar detalhes da CPU",
      options: [
        "Consultar detalhes da CPU",
        "Listar dispositivos conectados ao barramento PCI",
        "Listar módulos carregados no kernel",
        "Carregar o módulo dummy no cenário do laboratório",
      ],
      explanation:
        "Apresenta arquitetura, quantidade de CPUs e outros atributos.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "sistema-3",
      category: "sistema",
      level: 1,
      prompt: "Qual é a finalidade de lspci?",
      code: "lspci",
      answer: "Listar dispositivos conectados ao barramento PCI",
      options: [
        "Listar dispositivos conectados ao barramento PCI",
        "Listar módulos carregados no kernel",
        "Carregar o módulo dummy no cenário do laboratório",
        "Solicitar a remoção do módulo dummy",
      ],
      explanation: "Útil para identificar controladoras e placas.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "sistema-4",
      category: "sistema",
      level: 2,
      prompt: "Qual é a finalidade de lsmod?",
      code: "lsmod",
      answer: "Listar módulos carregados no kernel",
      options: [
        "Listar módulos carregados no kernel",
        "Carregar o módulo dummy no cenário do laboratório",
        "Solicitar a remoção do módulo dummy",
        "Consultar dados de memória expostos pelo kernel",
      ],
      explanation:
        "Mostra módulos atualmente carregados, não todos os disponíveis em disco.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "sistema-5",
      category: "sistema",
      level: 2,
      prompt: "Qual é a finalidade de modprobe dummy?",
      code: "modprobe dummy",
      answer: "Carregar o módulo dummy no cenário do laboratório",
      options: [
        "Carregar o módulo dummy no cenário do laboratório",
        "Solicitar a remoção do módulo dummy",
        "Consultar dados de memória expostos pelo kernel",
        "Consultar informações do kernel e da arquitetura",
      ],
      explanation:
        "Carregar o módulo e criar uma interface são etapas diferentes.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "sistema-6",
      category: "sistema",
      level: 3,
      prompt: "Qual é a finalidade de modprobe -r dummy?",
      code: "modprobe -r dummy",
      answer: "Solicitar a remoção do módulo dummy",
      options: [
        "Solicitar a remoção do módulo dummy",
        "Consultar dados de memória expostos pelo kernel",
        "Consultar informações do kernel e da arquitetura",
        "Consultar detalhes da CPU",
      ],
      explanation: "A remoção pode falhar se o módulo estiver em uso.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "sistema-7",
      category: "sistema",
      level: 2,
      prompt: "Qual é a finalidade de cat /proc/meminfo?",
      code: "cat /proc/meminfo",
      answer: "Consultar dados de memória expostos pelo kernel",
      options: [
        "Consultar dados de memória expostos pelo kernel",
        "Consultar informações do kernel e da arquitetura",
        "Consultar detalhes da CPU",
        "Listar dispositivos conectados ao barramento PCI",
      ],
      explanation: "/proc é um sistema de arquivos virtual.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "distros-1",
      category: "distros",
      level: 1,
      prompt: "Qual é a finalidade de apt?",
      code: "apt update",
      answer: "Gerenciar pacotes na família Debian",
      options: [
        "Gerenciar pacotes na família Debian",
        "Trabalhar diretamente com pacotes DEB",
        "Trabalhar com pacotes do formato RPM",
        "Gerenciar pacotes no ecossistema Fedora e Red Hat",
      ],
      explanation:
        "Debian, Ubuntu e Linux Mint utilizam ferramentas do ecossistema DEB.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "distros-2",
      category: "distros",
      level: 1,
      prompt: "Qual é a finalidade de dpkg?",
      code: "dpkg -l",
      answer: "Trabalhar diretamente com pacotes DEB",
      options: [
        "Trabalhar diretamente com pacotes DEB",
        "Trabalhar com pacotes do formato RPM",
        "Gerenciar pacotes no ecossistema Fedora e Red Hat",
        "Atualizar o índice local de pacotes",
      ],
      explanation: "É uma ferramenta de nível mais baixo que o APT.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "distros-3",
      category: "distros",
      level: 1,
      prompt: "Qual é a finalidade de rpm?",
      code: "rpm -qa",
      answer: "Trabalhar com pacotes do formato RPM",
      options: [
        "Trabalhar com pacotes do formato RPM",
        "Gerenciar pacotes no ecossistema Fedora e Red Hat",
        "Atualizar o índice local de pacotes",
        "Instalar um pacote e suas dependências resolvidas",
      ],
      explanation: "É associado no material à família Red Hat.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "distros-4",
      category: "distros",
      level: 2,
      prompt: "Qual é a finalidade de dnf?",
      code: "dnf install pacote",
      answer: "Gerenciar pacotes no ecossistema Fedora e Red Hat",
      options: [
        "Gerenciar pacotes no ecossistema Fedora e Red Hat",
        "Atualizar o índice local de pacotes",
        "Instalar um pacote e suas dependências resolvidas",
        "Atualizar pacotes instalados conforme as regras do APT",
      ],
      explanation:
        "O gerenciador disponível depende da distribuição e de sua versão.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "distros-5",
      category: "distros",
      level: 2,
      prompt: "Qual é a finalidade de apt update?",
      code: "apt update",
      answer: "Atualizar o índice local de pacotes",
      options: [
        "Atualizar o índice local de pacotes",
        "Instalar um pacote e suas dependências resolvidas",
        "Atualizar pacotes instalados conforme as regras do APT",
        "Gerenciar pacotes na família Debian",
      ],
      explanation:
        "Não instala automaticamente todas as novas versões dos pacotes.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "distros-6",
      category: "distros",
      level: 2,
      prompt: "Qual é a finalidade de apt install?",
      code: "apt install figlet",
      answer: "Instalar um pacote e suas dependências resolvidas",
      options: [
        "Instalar um pacote e suas dependências resolvidas",
        "Atualizar pacotes instalados conforme as regras do APT",
        "Gerenciar pacotes na família Debian",
        "Trabalhar diretamente com pacotes DEB",
      ],
      explanation: "Exige índices e repositórios adequadamente configurados.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "distros-7",
      category: "distros",
      level: 3,
      prompt: "Qual é a finalidade de apt upgrade?",
      code: "apt upgrade",
      answer: "Atualizar pacotes instalados conforme as regras do APT",
      options: [
        "Atualizar pacotes instalados conforme as regras do APT",
        "Gerenciar pacotes na família Debian",
        "Trabalhar diretamente com pacotes DEB",
        "Trabalhar com pacotes do formato RPM",
      ],
      explanation: "É diferente de atualizar apenas o índice com apt update.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "cenario-0",
      category: "permissoes",
      level: 3,
      prompt:
        "Um diretório de equipe deve herdar o grupo e restringir exclusões entre colegas. Quais bits combinar?",
      code: "",
      answer: "SGID e sticky bit",
      options: [
        "SGID e sticky bit",
        "SUID e somente leitura",
        "Apenas SUID",
        "Somente chmod 777",
      ],
      explanation:
        "SGID transmite o grupo do diretório; sticky restringe exclusão e renomeação. As permissões de escrita e acesso ainda precisam ser configuradas.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "cenario-1",
      category: "permissoes",
      level: 2,
      prompt:
        "O arquivo tem modo 640. Quem pode escrever nele pelas permissões tradicionais?",
      code: "",
      answer: "Somente o proprietário",
      options: [
        "Somente o proprietário",
        "Dono e grupo",
        "Todos os usuários",
        "Somente outros",
      ],
      explanation:
        "6 corresponde a rw-, 4 a r-- e 0 a ---. Privilégios administrativos e ACLs são questões separadas.",
      source: "Permissões de Usuários.pdf",
    },
    {
      id: "cenario-2",
      category: "usuarios",
      level: 3,
      prompt:
        "Um colega precisa entrar em um novo grupo sem perder os grupos suplementares atuais. Qual opção usar?",
      code: "",
      answer: "usermod -aG",
      options: [
        "usermod -aG",
        "usermod -G sem -a",
        "userdel -r",
        "groupadd -r",
      ],
      explanation:
        "O acréscimo com -aG preserva os demais grupos suplementares.",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      id: "cenario-3",
      category: "texto",
      level: 3,
      prompt:
        "Você quer guardar novos erros sem apagar os erros anteriores. Qual operador escolher?",
      code: "",
      answer: "2>>",
      options: ["2>>", "2>", ">", "<"],
      explanation: "2 seleciona stderr e >> acrescenta ao arquivo.",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      id: "cenario-4",
      category: "redes",
      level: 3,
      prompt:
        "O cliente não acessa o servidor. Qual investigação inicial evita mudar configurações às cegas?",
      code: "",
      answer: "Consultar endereços e rotas; depois testar conectividade",
      options: [
        "Consultar endereços e rotas; depois testar conectividade",
        "Apagar todas as interfaces",
        "Liberar acesso root por SSH",
        "Reinstalar o sistema imediatamente",
      ],
      explanation:
        "O diagnóstico começa pela observação do endereço, do caminho de rede e da comunicação.",
      source: "Jonathan Eleodoro - Exercício 2 - Cliente _ Servidor.pdf",
    },
    {
      id: "cenario-5",
      category: "ssh",
      level: 3,
      prompt:
        "Qual prática do laboratório SSH não deve ser copiada automaticamente para um servidor exposto à internet?",
      code: "",
      answer: "Habilitar login remoto direto como root",
      options: [
        "Habilitar login remoto direto como root",
        "Consultar o estado do serviço",
        "Usar conexão criptografada",
        "Consultar a configuração do cliente",
      ],
      explanation:
        "O próprio material delimita a habilitação de root ao ambiente de teste.",
      source: "SSH (3).pdf",
    },
    {
      id: "cenario-6",
      category: "sistema",
      level: 3,
      prompt:
        "Um serviço executa no espaço de usuário. Quem gerencia memória e dispositivos abaixo dele?",
      code: "",
      answer: "Kernel",
      options: [
        "Kernel",
        "GRUB durante toda a execução",
        "Apenas o terminal",
        "O arquivo de log",
      ],
      explanation: "O material separa espaço de usuário, kernel e hardware.",
      source: "Apresentação sem título.pdf",
    },
    {
      id: "cenario-7",
      category: "distros",
      level: 3,
      prompt:
        "Um comando usa apt em Debian. Qual conclusão é adequada para outra distribuição?",
      code: "",
      answer: "Verificar a família e o gerenciador disponível",
      options: [
        "Verificar a família e o gerenciador disponível",
        "Substituir apt por rpm mantendo todas as opções",
        "Toda distribuição usa APT",
        "O formato DEB funciona nativamente em todas",
      ],
      explanation:
        "O material distingue os ecossistemas DEB e RPM. As interfaces não são intercambiáveis.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      id: "cenario-8",
      category: "arquivos",
      level: 3,
      prompt:
        "Você precisa remover uma pasta somente se ela estiver vazia. Qual escolha expressa essa intenção?",
      code: "",
      answer: "rmdir pasta",
      options: [
        "rmdir pasta",
        "rm -rf pasta",
        "touch pasta",
        "cp -r pasta backup",
      ],
      explanation:
        "rmdir falha quando há conteúdo, em vez de removê-lo recursivamente.",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
  ],
  manual: [
    {
      category: "arquivos",
      command: "pwd",
      action: "Mostrar o caminho completo do diretório atual",
      explanation: "Mostra o diretório de trabalho atual.",
      example: "pwd",
      source: "Jonathan Eleodoro - Exercícios.pdf",
    },
    {
      category: "arquivos",
      command: "ls -la",
      action: "Listar detalhes e arquivos ocultos",
      explanation:
        "-l usa o formato longo; -a inclui entradas iniciadas com ponto.",
      example: "ls -la",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "cd ..",
      action: "Subir um nível na árvore de diretórios",
      explanation: ".. representa o diretório pai.",
      example: "cd ..",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "cd ~",
      action: "Voltar ao diretório pessoal",
      explanation: "O shell expande ~ para o diretório pessoal do usuário.",
      example: "cd ~",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "mkdir -p",
      action: "Criar uma hierarquia de diretórios",
      explanation: "-p cria os diretórios pais necessários.",
      example: "mkdir -p projeto/aulas",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "rmdir",
      action: "Remover um diretório vazio",
      explanation: "Falha se o diretório tiver conteúdo.",
      example: "rmdir vazio",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "touch",
      action: "Criar um arquivo vazio inexistente",
      explanation:
        "Se o arquivo existe, touch atualiza seus timestamps; não apaga seu conteúdo.",
      example: "touch aula.txt",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "cp -r",
      action: "Copiar uma árvore de diretórios",
      explanation: "-r percorre os subdiretórios recursivamente.",
      example: "cp -r projeto copia",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "mv",
      action: "Mover ou renomear um arquivo",
      explanation: "O destino determina se haverá mudança de local ou de nome.",
      example: "mv aula.txt revisao.txt",
      source: "Jonathan Eleodoro - Exercícios.pdf",
    },
    {
      category: "arquivos",
      command: "rm -r",
      action: "Remover um diretório e seu conteúdo",
      explanation:
        "A remoção é recursiva. Confira o caminho antes de executar em um sistema real.",
      example: "rm -r teste",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "find",
      action: "Localizar arquivos pelo nome",
      explanation: "A busca percorre a árvore a partir do caminho indicado.",
      example: 'find /etc -name "*.conf"',
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "arquivos",
      command: "cd -",
      action: "Voltar ao diretório anterior",
      explanation:
        "Usa o diretório de trabalho anterior armazenado pelo shell.",
      example: "cd -",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "texto",
      command: "cat",
      action: "Exibir ou concatenar conteúdo de arquivos",
      explanation: "Lê os arquivos e escreve seu conteúdo na saída padrão.",
      example: "cat aula.txt",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "head -n 3",
      action: "Mostrar as três primeiras linhas",
      explanation: "-n define a quantidade de linhas iniciais.",
      example: "head -n 3 /etc/passwd",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "texto",
      command: "tail -n 10",
      action: "Mostrar as dez últimas linhas",
      explanation: "Útil para consultar o final de um arquivo de log.",
      example: "tail -n 10 /var/log/syslog",
      source: "Jonathan Eleodoro - Exercícios.pdf",
    },
    {
      category: "texto",
      command: "grep",
      action: "Selecionar linhas que correspondem a um padrão",
      explanation: "Filtra linhas; não altera o arquivo de entrada.",
      example: "grep error sistema.log",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "sort",
      action: "Ordenar linhas de texto",
      explanation: "A ordem depende da localidade; números podem exigir -n.",
      example: "sort nomes.txt",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "wc -l",
      action: "Contar linhas delimitadas por nova linha",
      explanation: "Conta os caracteres de nova linha da entrada.",
      example: "wc -l nomes.txt",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: ">",
      action: "Redirecionar a saída padrão sobrescrevendo o destino",
      explanation: "Cria o arquivo ou trunca o existente antes da execução.",
      example: "ls -la > lista.txt",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: ">>",
      action: "Acrescentar a saída padrão ao final do destino",
      explanation: "Preserva o conteúdo anterior e acrescenta a nova saída.",
      example: "date >> registro.txt",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "<",
      action: "Ler a entrada padrão a partir de um arquivo",
      explanation:
        "O programa recebe o conteúdo do arquivo pela entrada padrão.",
      example: "sort < nomes.txt",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "|",
      action: "Conectar a saída padrão à entrada do próximo comando",
      explanation: "O pipe transporta dados; erros não entram nele por padrão.",
      example: "cat nomes.txt | sort",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "2>",
      action: "Redirecionar apenas a saída de erro sobrescrevendo o destino",
      explanation: "O descritor 2 corresponde à saída de erro.",
      example: "cat ausente.txt 2> erros.log",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "2>>",
      action: "Acrescentar apenas a saída de erro ao destino",
      explanation: "Combina o descritor 2 com o operador de acréscimo.",
      example: "cat ausente.txt 2>> erros.log",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "&>",
      action: "Redirecionar saída padrão e erros no Bash",
      explanation: "É sintaxe do Bash; não deve ser presumida para todo shell.",
      example: "ls /ausente &> tudo.log",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "tee",
      action: "Exibir a saída e gravá-la em arquivo",
      explanation: "Recebe entrada padrão e a copia para a tela e o arquivo.",
      example: "ls | tee lista.txt",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "texto",
      command: "&&",
      action: "Executar o próximo comando apenas se o anterior tiver sucesso",
      explanation: "O shell verifica o status de saída zero.",
      example: "mkdir projeto && cd projeto",
      source: "Jonathan Eleodoro - Exercícios.docx.pdf",
    },
    {
      category: "permissoes",
      command: "chmod",
      action: "Alterar permissões de acesso",
      explanation: "Aceita modos simbólicos e octais.",
      example: "chmod 640 documento.txt",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chown",
      action: "Alterar o proprietário de um arquivo",
      explanation: "Pode também alterar o grupo usando dono:grupo.",
      example: "chown aluno:turma documento.txt",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chgrp",
      action: "Alterar somente o grupo proprietário",
      explanation: "Mantém o usuário proprietário.",
      example: "chgrp turma documento.txt",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chmod 750",
      action: "Conceder rwx ao dono, r-x ao grupo e nada aos outros",
      explanation: "Os valores r=4, w=2 e x=1 são somados em cada classe.",
      example: "chmod 750 projeto",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chmod g+x",
      action: "Adicionar execução ao grupo sem alterar os demais bits",
      explanation:
        "A operação simbólica + preserva as permissões não mencionadas.",
      example: "chmod g+x programa",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chmod o-w",
      action: "Retirar escrita dos outros usuários",
      explanation: "o indica outros; -w remove somente escrita.",
      example: "chmod o-w documento.txt",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chmod +t",
      action: "Ativar o sticky bit em um diretório",
      explanation:
        "Restringe exclusão e renomeação ao dono do arquivo, dono do diretório ou usuário privilegiado. As permissões normais continuam valendo.",
      example: "chmod +t compartilhado",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chmod g+s",
      action: "Ativar SGID em um diretório compartilhado",
      explanation:
        "Novos arquivos herdam o grupo do diretório; isso não concede escrita automaticamente.",
      example: "chmod g+s projeto",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "chmod u+s",
      action: "Ativar SUID em um executável",
      explanation:
        "Em executáveis compatíveis, pode mudar o UID efetivo para o dono. Não use como solução geral de acesso.",
      example: "chmod u+s programa",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "permissoes",
      command: "umask 077",
      action: "Restringir permissões iniciais de novos arquivos ao dono",
      explanation:
        "Com bases usuais 666 e 777, resulta em arquivos 600 e diretórios 700. A máscara remove bits.",
      example: "umask 077",
      source: "Permissões de Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "whoami",
      action: "Exibir o nome do usuário efetivo",
      explanation:
        "Identifica o usuário associado à identidade efetiva do processo.",
      example: "whoami",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "id",
      action: "Consultar UID, GID e grupos de um usuário",
      explanation: "Sem argumento consulta o usuário atual.",
      example: "id aluno",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "who",
      action: "Listar sessões de usuários conectados",
      explanation: "Não é uma lista de todas as contas cadastradas.",
      example: "who",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "useradd",
      action: "Criar uma conta de usuário",
      explanation: "Opções como -m e -s controlam diretório pessoal e shell.",
      example: "useradd -m aluno",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "passwd",
      action: "Definir ou alterar a senha de uma conta",
      explanation:
        "Alterar senha de outro usuário exige privilégios adequados.",
      example: "passwd aluno",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "groupadd",
      action: "Criar um grupo",
      explanation: "Depois da criação, o grupo pode receber membros.",
      example: "groupadd laboratorio",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "usermod -aG",
      action: "Acrescentar um grupo suplementar preservando os demais",
      explanation:
        "-a acrescenta; -G informa os grupos suplementares. Sem -a, a lista pode ser substituída.",
      example: "usermod -aG laboratorio aluno",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "userdel -r",
      action: "Excluir conta e remover seu diretório pessoal",
      explanation:
        "Revise dados e faça backup antes de excluir. Não procura todo arquivo do usuário no sistema.",
      example: "userdel -r aluno",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "chage -d 0",
      action: "Exigir alteração da senha no próximo login",
      explanation: "Define a última troca de senha para o início da contagem.",
      example: "chage -d 0 aluno",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "usuarios",
      command: "groupmod -n",
      action: "Renomear um grupo existente",
      explanation: "O novo nome vem antes do nome atual.",
      example: "groupmod -n infra suporte",
      source: "Jonathan Eleodoro - Exercícios Grupos e Usuários.pdf",
    },
    {
      category: "processos",
      command: "ps aux",
      action: "Obter uma fotografia dos processos",
      explanation:
        "É uma consulta pontual, não uma tela atualizada continuamente.",
      example: "ps aux",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "processos",
      command: "top",
      action: "Acompanhar processos em uma tela atualizada",
      explanation: "Mostra atividade e consumo de recursos.",
      example: "top",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "processos",
      command: "htop",
      action: "Explorar processos em uma interface interativa",
      explanation: "Pode precisar de instalação; a disponibilidade varia.",
      example: "htop",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "processos",
      command: "jobs",
      action: "Listar os jobs do shell atual",
      explanation: "Não lista todos os processos de todos os usuários.",
      example: "jobs",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "processos",
      command: "fg",
      action: "Trazer um job ao primeiro plano",
      explanation: "O shell passa a aguardar o job selecionado.",
      example: "fg %1",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "processos",
      command: "bg",
      action: "Retomar um job suspenso em segundo plano",
      explanation: "Trabalha com os jobs controlados pelo shell atual.",
      example: "bg %1",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "processos",
      command: "kill -TERM",
      action: "Solicitar encerramento de um processo por sinal",
      explanation:
        "SIGTERM pode ser tratado pelo processo para encerrar de forma organizada.",
      example: "kill -TERM 1234",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "processos",
      command: "kill -KILL",
      action: "Forçar o término de um processo sem tratamento do sinal",
      explanation:
        "SIGKILL não pode ser capturado pelo processo. Evite como primeira tentativa.",
      example: "kill -KILL 1234",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "redes",
      command: "ip addr",
      action: "Consultar endereços das interfaces",
      explanation: "Exibe endereços e informações associadas às interfaces.",
      example: "ip addr",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "ip route",
      action: "Consultar a tabela de rotas",
      explanation: "Mostra caminhos e o gateway padrão quando configurado.",
      example: "ip route",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "redes",
      command: "ping",
      action: "Testar resposta a mensagens ICMP de eco",
      explanation:
        "Ausência de resposta não prova indisponibilidade: ICMP pode estar filtrado.",
      example: "ping -c 4 192.168.1.10",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "ss",
      action: "Consultar sockets de rede",
      explanation:
        "Pode mostrar conexões e portas em escuta conforme as opções.",
      example: "ss -lnt",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "ip link show",
      action: "Exibir interfaces e atributos de enlace",
      explanation: "Ajuda a observar estado e endereços MAC.",
      example: "ip link show",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "ip link set dev enp0s3 up",
      action: "Ativar administrativamente uma interface",
      explanation: "A ativação não configura, por si só, endereço IP ou rota.",
      example: "ip link set dev enp0s3 up",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "tcpdump -i eth0 icmp",
      action: "Capturar tráfego ICMP em uma interface",
      explanation:
        "O filtro icmp seleciona esse protocolo. Capturas reais exigem autorização e privilégios apropriados.",
      example: "tcpdump -i eth0 icmp",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "tcpdump -c 50 -i eth0",
      action: "Limitar uma captura a cinquenta pacotes",
      explanation: "-c define a quantidade antes do encerramento.",
      example: "tcpdump -c 50 -i eth0",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "tcpdump -n -i eth0",
      action: "Capturar sem resolver endereços para nomes",
      explanation: "-n evita a conversão de endereços em nomes.",
      example: "tcpdump -n -i eth0",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "tcpdump -i eth0 port 53",
      action: "Filtrar tráfego associado à porta 53",
      explanation:
        "O filtro usa a porta; não garante que todo pacote seja uma consulta DNS legítima.",
      example: "tcpdump -i eth0 port 53",
      source: "Comandos de redes.pptx (1).pdf",
    },
    {
      category: "redes",
      command: "nslookup",
      action: "Consultar informações DNS",
      explanation: "Permite consultar nomes junto a um servidor DNS.",
      example: "nslookup servidor.exemplo",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "redes",
      command: "dig",
      action: "Inspecionar respostas DNS detalhadas",
      explanation: "Mostra informações da consulta e registros retornados.",
      example: "dig servidor.exemplo",
      source: "Plano_de_Trabalho_Linux_2026.pdf",
    },
    {
      category: "redes",
      command: "ip netns add",
      action: "Criar um namespace de rede",
      explanation:
        "Permite isolar interfaces, rotas e outros recursos de rede.",
      example: "ip netns add pc1",
      source: "Jonathan Eleodoro - Projeto.pdf",
    },
    {
      category: "ssh",
      command: "ssh aluno@192.168.1.10",
      action: "Iniciar uma sessão SSH como aluno",
      explanation: "O cliente conecta ao servidor usando o usuário indicado.",
      example: "ssh aluno@192.168.1.10",
      source: "SSH (3).pdf",
    },
    {
      category: "ssh",
      command: "systemctl status ssh",
      action: "Consultar o estado do serviço SSH no cenário Debian",
      explanation: "O nome da unidade pode variar entre distribuições.",
      example: "systemctl status ssh",
      source: "SSH (3).pdf",
    },
    {
      category: "ssh",
      command: "systemctl start ssh",
      action: "Iniciar o serviço SSH no cenário Debian",
      explanation: "Iniciar agora não é o mesmo que habilitar no boot.",
      example: "systemctl start ssh",
      source: "SSH (3).pdf",
    },
    {
      category: "ssh",
      command: "su -",
      action: "Abrir uma sessão de login do usuário root",
      explanation:
        "O hífen solicita ambiente de login; não é equivalente a preservar o ambiente da sessão atual.",
      example: "su -",
      source: "Su -   e Visudo.pdf",
    },
    {
      category: "ssh",
      command: "sudo",
      action: "Executar um comando com a identidade autorizada pela política",
      explanation:
        "O acesso depende da configuração; não é uma permissão ilimitada para qualquer usuário.",
      example: "sudo whoami",
      source: "Su -   e Visudo.pdf",
    },
    {
      category: "ssh",
      command: "visudo",
      action: "Editar a política sudoers com verificação de sintaxe",
      explanation:
        "Ajuda a evitar erros de sintaxe na política administrativa.",
      example: "visudo",
      source: "Su -   e Visudo.pdf",
    },
    {
      category: "ssh",
      command: "nginx -t",
      action: "Testar a configuração do Nginx antes de reiniciar",
      explanation:
        "Verifique a validação antes de aplicar uma mudança no serviço.",
      example: "nginx -t",
      source:
        "Jonathan Eleodoro - Atividade - Aula 3 Dois Servidores Virtuais.pdf",
    },
    {
      category: "ssh",
      command: "curl",
      action: "Consultar uma URL a partir do terminal",
      explanation:
        "No laboratório, permite testar a resposta do servidor HTTP.",
      example: "curl http://10.0.0.100",
      source:
        "Jonathan Eleodoro - Atividade - Aula 3 Dois Servidores Virtuais.pdf",
    },
    {
      category: "sistema",
      command: "uname -a",
      action: "Consultar informações do kernel e da arquitetura",
      explanation:
        "Mostra diversos dados do sistema; não substitui uma identificação completa da distribuição.",
      example: "uname -a",
      source: "Apresentação sem título.pdf",
    },
    {
      category: "sistema",
      command: "lscpu",
      action: "Consultar detalhes da CPU",
      explanation:
        "Apresenta arquitetura, quantidade de CPUs e outros atributos.",
      example: "lscpu",
      source: "Apresentação sem título.pdf",
    },
    {
      category: "sistema",
      command: "lspci",
      action: "Listar dispositivos conectados ao barramento PCI",
      explanation: "Útil para identificar controladoras e placas.",
      example: "lspci",
      source: "Apresentação sem título.pdf",
    },
    {
      category: "sistema",
      command: "lsmod",
      action: "Listar módulos carregados no kernel",
      explanation:
        "Mostra módulos atualmente carregados, não todos os disponíveis em disco.",
      example: "lsmod",
      source: "Apresentação sem título.pdf",
    },
    {
      category: "sistema",
      command: "modprobe dummy",
      action: "Carregar o módulo dummy no cenário do laboratório",
      explanation:
        "Carregar o módulo e criar uma interface são etapas diferentes.",
      example: "modprobe dummy",
      source: "Apresentação sem título.pdf",
    },
    {
      category: "sistema",
      command: "modprobe -r dummy",
      action: "Solicitar a remoção do módulo dummy",
      explanation: "A remoção pode falhar se o módulo estiver em uso.",
      example: "modprobe -r dummy",
      source: "Apresentação sem título.pdf",
    },
    {
      category: "sistema",
      command: "cat /proc/meminfo",
      action: "Consultar dados de memória expostos pelo kernel",
      explanation: "/proc é um sistema de arquivos virtual.",
      example: "cat /proc/meminfo",
      source: "Apresentação sem título.pdf",
    },
    {
      category: "distros",
      command: "apt",
      action: "Gerenciar pacotes na família Debian",
      explanation:
        "Debian, Ubuntu e Linux Mint utilizam ferramentas do ecossistema DEB.",
      example: "apt update",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "distros",
      command: "dpkg",
      action: "Trabalhar diretamente com pacotes DEB",
      explanation: "É uma ferramenta de nível mais baixo que o APT.",
      example: "dpkg -l",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "distros",
      command: "rpm",
      action: "Trabalhar com pacotes do formato RPM",
      explanation: "É associado no material à família Red Hat.",
      example: "rpm -qa",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "distros",
      command: "dnf",
      action: "Gerenciar pacotes no ecossistema Fedora e Red Hat",
      explanation:
        "O gerenciador disponível depende da distribuição e de sua versão.",
      example: "dnf install pacote",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "distros",
      command: "apt update",
      action: "Atualizar o índice local de pacotes",
      explanation:
        "Não instala automaticamente todas as novas versões dos pacotes.",
      example: "apt update",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "distros",
      command: "apt install",
      action: "Instalar um pacote e suas dependências resolvidas",
      explanation: "Exige índices e repositórios adequadamente configurados.",
      example: "apt install figlet",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
    {
      category: "distros",
      command: "apt upgrade",
      action: "Atualizar pacotes instalados conforme as regras do APT",
      explanation: "É diferente de atualizar apenas o índice com apt update.",
      example: "apt upgrade",
      source: "_Aula 2 Comandos iniciais.pdf",
    },
  ],
};
