"use strict";
/* Conteúdo exclusivo entregue pela API após verificar direito Premium no MySQL. */
const source = "Linux_Flow · extensão prática Premium";
const questions = [
  { id: "pro-auto-01", category: "scripts", level: 4, prompt: "Um script precisa parar se um comando obrigatório falhar. Qual estrutura testa o status imediatamente?", code: "comando", answer: "if ! comando; then exit 1; fi", options: ["if ! comando; then exit 1; fi", "comando; exit 0", "echo comando; continue", "touch comando; exit 0"], explanation: "A condição invertida identifica a falha e encerra com status diferente de zero." },
  { id: "pro-auto-02", category: "scripts", level: 4, prompt: "Qual forma preserva espaços em um argumento recebido pelo script?", code: "arquivo=$1", answer: "cat \"$arquivo\"", options: ["cat \"$arquivo\"", "cat $arquivo", "cat arquivo", "cat '$arquivo'"], explanation: "Aspas duplas mantêm a expansão da variável como um único argumento." },
  { id: "pro-auto-03", category: "scripts", level: 4, prompt: "Como percorrer cada argumento recebido, preservando espaços dentro de cada um?", code: "", answer: "for item in \"$@\"; do ...; done", options: ["for item in \"$@\"; do ...; done", "for item in $*; do ...; done", "for item in $1; do ...; done", "for item in args; do ...; done"], explanation: "A expansão entre aspas de $@ mantém os limites dos argumentos posicionais." },
  { id: "pro-auto-04", category: "scripts", level: 4, prompt: "Um job gera um arquivo novo e só deve substituir o final quando terminar. Qual padrão reduz a chance de deixar arquivo parcial?", code: "", answer: "Escrever temporário e renomear após sucesso", options: ["Escrever temporário e renomear após sucesso", "Sobrescrever o final antes de calcular", "Ignorar o status de saída", "Executar o job duas vezes em paralelo"], explanation: "Preparar um temporário e promover após sucesso evita expor um resultado incompleto." },
  { id: "pro-auto-05", category: "scripts", level: 4, prompt: "Qual comando mostra o status da última execução no Bash?", code: "false", answer: "echo $?", options: ["echo $?", "echo $1", "echo $$", "echo $PATH"], explanation: "$? contém o código de saída da última execução." },
  { id: "pro-auto-06", category: "arquivos_compactados", level: 4, prompt: "Antes de automatizar a extração de um tar recebido, qual verificação é útil?", code: "backup.tar", answer: "Listar entradas e examinar caminhos", options: ["Listar entradas e examinar caminhos", "Conceder chmod 777 ao arquivo", "Apagar a cópia original", "Executar todos os arquivos extraídos"], explanation: "A listagem prévia ajuda a identificar caminhos inesperados." },
  { id: "pro-auto-07", category: "scripts", level: 4, prompt: "Um script será executado periodicamente. O que ajuda a diagnosticar falhas posteriores?", code: "", answer: "Registrar saídas e códigos de erro relevantes", options: ["Registrar saídas e códigos de erro relevantes", "Silenciar todas as falhas", "Eliminar validações de entrada", "Usar nomes aleatórios para arquivos de log"], explanation: "Registros claros mostram o que falhou e em qual etapa." },
  { id: "pro-auto-08", category: "arquivos", level: 4, prompt: "Um nome de arquivo veio do usuário. Qual prática evita que espaços o dividam em vários argumentos?", code: "arquivo=\"meu relatório.txt\"", answer: "Usar \"$arquivo\" na chamada", options: ["Usar \"$arquivo\" na chamada", "Usar $arquivo sem aspas", "Substituir todo espaço por ;", "Adicionar eval antes do comando"], explanation: "Aspas na expansão evitam separação indesejada de palavras." },
  { id: "pro-auto-09", category: "scripts", level: 4, prompt: "Uma tarefa deve poder ser repetida sem duplicar dados. Qual propriedade é desejada?", code: "", answer: "Idempotência", options: ["Idempotência", "Aleatoriedade obrigatória", "Dependência de cliques manuais", "Ausência de registros"], explanation: "Uma operação idempotente produz o mesmo estado esperado quando repetida." },
  { id: "pro-auto-10", category: "scripts", level: 4, prompt: "Uma automação precisa de senha para acessar um serviço. Onde é mais prudente guardá-la?", code: "", answer: "Em mecanismo de segredos fora do script versionado", options: ["Em mecanismo de segredos fora do script versionado", "Diretamente no código publicado", "No nome do arquivo do script", "Em comentário no repositório público"], explanation: "Segredos não devem ser incorporados ao código distribuído." },
  { id: "pro-arch-01", category: "redes", level: 5, prompt: "Um serviço responde em 127.0.0.1:80, mas não externamente. Qual hipótese verificar primeiro?", code: "", answer: "Ele pode estar escutando só na interface local", options: ["Ele pode estar escutando só na interface local", "O disco está obrigatoriamente cheio", "O DNS local sempre falhou", "O shell não suporta variáveis"], explanation: "Um bind em loopback não atende conexões dirigidas à interface externa." },
  { id: "pro-arch-02", category: "redes", level: 5, prompt: "A rota padrão está ausente. Qual tráfego tende a ser afetado?", code: "", answer: "Destinos fora das redes diretamente conectadas", options: ["Destinos fora das redes diretamente conectadas", "Todo acesso a arquivo local", "A leitura de stdout", "A execução de pwd"], explanation: "Sem rota padrão, destinos sem rota mais específica não têm próximo salto." },
  { id: "pro-arch-03", category: "permissoes", level: 5, prompt: "Um processo precisa ler um arquivo privado. Qual ajuste segue o menor privilégio?", code: "", answer: "Conceder somente leitura ao usuário ou grupo necessário", options: ["Conceder somente leitura ao usuário ou grupo necessário", "Aplicar chmod 777", "Executar todo serviço como root", "Desativar logs de acesso"], explanation: "Conceda apenas a capacidade necessária à identidade que executa o processo." },
  { id: "pro-arch-04", category: "processos", level: 5, prompt: "Um serviço falha logo após iniciar. Qual sequência de investigação é mais informativa?", code: "", answer: "Verificar status e registros antes de alterar configuração", options: ["Verificar status e registros antes de alterar configuração", "Reiniciar indefinidamente sem observar erros", "Apagar arquivos do serviço", "Trocar permissões de todo o sistema"], explanation: "Status e registros ajudam a localizar a causa antes da intervenção." },
  { id: "pro-arch-05", category: "redes", level: 5, prompt: "Um nome não resolve, mas o IP do serviço responde. Qual componente merece investigação?", code: "", answer: "Resolução de nomes", options: ["Resolução de nomes", "Permissão de execução do shell", "Formato do arquivo tar", "Relógio do terminal simulado"], explanation: "A diferença entre acesso por nome e por IP aponta para resolução de nomes." },
  { id: "pro-arch-06", category: "ssh", level: 5, prompt: "Antes de alterar remotamente a regra que permite SSH, qual precaução evita perder acesso?", code: "", answer: "Manter sessão de recuperação e validar a regra antes de aplicá-la", options: ["Manter sessão de recuperação e validar a regra antes de aplicá-la", "Fechar a única sessão ativa imediatamente", "Desativar todos os registros", "Trocar a chave sem testar login"], explanation: "Um caminho de recuperação e validação reduzem o risco de bloqueio remoto." },
  { id: "pro-arch-07", category: "redes", level: 5, prompt: "O serviço responde localmente, mas não pela rede. Quais camadas vale comparar?", code: "", answer: "Bind, firewall, rota e endereço de destino", options: ["Bind, firewall, rota e endereço de destino", "Somente o tema do terminal", "A extensão de um arquivo tar", "A ordem das alternativas do quiz"], explanation: "A falha pode estar na escuta, filtragem ou no caminho até o serviço." },
  { id: "pro-arch-08", category: "sistema", level: 5, prompt: "Por que monitorar espaço livre em um serviço que grava logs?", code: "", answer: "O volume cheio pode impedir novas escritas", options: ["O volume cheio pode impedir novas escritas", "A CPU deixa de ter núcleos", "O IP muda automaticamente", "As permissões deixam de existir"], explanation: "Sem espaço, logs e outros dados podem não ser gravados." },
  { id: "pro-arch-09", category: "usuarios", level: 5, prompt: "Dois serviços não precisam compartilhar dados. Qual separação ajuda a limitar impacto?", code: "", answer: "Executá-los sob identidades e permissões distintas", options: ["Executá-los sob identidades e permissões distintas", "Usar a mesma conta privilegiada para ambos", "Aplicar escrita global em todos os diretórios", "Remover verificações de acesso"], explanation: "Isolar identidades limita o acesso de cada serviço aos próprios recursos." },
  { id: "pro-arch-10", category: "sistema", level: 5, prompt: "Uma mudança de configuração falhou em produção. O que deveria constar em um plano de implantação?", code: "", answer: "Validação, observação e possibilidade de reversão", options: ["Validação, observação e possibilidade de reversão", "Apenas o horário de início", "Remoção de backups antes da mudança", "Publicação sem registro da versão anterior"], explanation: "Testes, métricas e rollback permitem detectar e corrigir impactos." },
].map((question) => ({ ...question, source }));
module.exports = { questions };
